### ISSUE TITLE
Negative Zahlen?

### ISSUE THREAD

**Issue by groehner** [romangraef/remaspedit#1]
Bei dem im hessischen Landesabitur verwendeten Modell der Registermaschine werden in den Registern natürliche Zahlen gespeichert. 
Daher ist der SUB x Befehl so definiert: Subtrahiert x vom Akkumulator. Ist der Wert von x größer als der des Akkumulators, ist das Ergebnis 0.
Ich halte daher eine Unterstützung von negativen Zahlen für kontraproduktiv.

**Comment by lineargraph** [comment]
Das Originalverhalten von SUB wird weiterhin beibehalten, das neue Verhalten ist ein expliziter Opt-In per Program: 
```
ALLOWNEG
LOAD #1 
SUB #2
END
```
resultiert in `-1`, entfernt man das erste `ALLOWNEG` bleibt es bei Akkumulator = `0`, wie im Original-ReMaSp. Dementsprechend würde ich in Klassen die auf das hessische Landesabitur vorbereiten natürlich nicht empfehlen `ALLOWNEG` einzusetzen.
